# Лабораторная работа №1
## Выполнил студент группы БВТ2204 Налтакян Карина

### Оглавление
1. [Задание 1](#Задание-№1)
2. [Задание 2](#Задание-№2)
3. [Задание 3](#Задание-№3)
4. [Вывод](#Вывод)

### Задание №1
<i> Вызвать функцию print() и передать туда строку Hello, World! </i>

In [2]:
print("Hello,world!")

Hello,world!


### Задание №2
Написать генератор случайных матриц(многомерных), который принимает
опциональные параметры <b>m</b>, <b>n</b>, <b>min_limit</b>, <b>max_limit</b>, где <b>m</b> и <b>n</b> указывают размер
матрицы, а <b>min_lim</b> и <b>max_lim</b> - минимальное и максимальное значение для
генерируемого числа.

In [1]:
import random
import time
import numpy as np

In [14]:
user_m = int(input())
user_n = int(input())
user_min_limit = int(input())
user_max_limit = int(input())

def matrix_generate(user_m, user_n, user_min_limit, user_max_limit): 
    matrix = np.random.randint(user_min_limit, user_max_limit, size=(user_m, user_n)) 
    return matrix 

matrix = matrix_generate(user_m, user_n, user_min_limit, user_max_limit)
print(matrix)
    

 100
 100
 200
 450


[[445 267 437 ... 272 389 398]
 [280 388 405 ... 291 291 386]
 [377 242 228 ... 395 220 239]
 ...
 [411 356 222 ... 427 443 331]
 [264 388 393 ... 249 391 429]
 [317 433 255 ... 311 419 401]]


### Задание №3
Реализовать методы сортировки строк числовой матрицы в соответствии с
заданием. Оценить время работы каждого алгоритма сортировки и сравнить его со
временем стандартной функции сортировки. Испытания проводить на сгенерированных
матрицах.

In [15]:
import copy

In [16]:
# Сортировка выбором.
# Берётся срез массива, в котором минимальный элемент переносят в самый левый угол,
# после чего срез уменьшается и цикл повторяется.
start_time = time.time()

list1 = matrix.copy()

for row in list1:
    for i in range(len(row)-1):
        srez = row[i:]
        mi = min(srez)
        mii = np.where(srez == mi)[0]
        srez[0],srez[mii] = mi, srez[0]
print(list1)

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[203 205 210 ... 446 446 446]
 [201 211 213 ... 449 449 449]
 [203 204 205 ... 443 443 443]
 ...
 [200 211 212 ... 449 449 449]
 [207 211 216 ... 441 441 449]
 [200 202 203 ... 448 448 448]]
--- 164 ms ---


In [17]:
# Сортировка вставкой.
start_time = time.time()

list2 = matrix.copy()

for row in list2:
    for i in range(len(row)):
        while i > 0 and row[i] < row[i-1]:
            row[i], row[i-1] = row[i-1], row[i]
            i -= 1

print(list2)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[203 205 210 ... 441 445 446]
 [201 211 213 ... 444 445 449]
 [203 204 205 ... 442 442 443]
 ...
 [200 211 212 ... 443 448 449]
 [207 211 216 ... 440 441 449]
 [200 202 203 ... 442 445 448]]
--- 362 ms ---


In [18]:
# Сортировка обменом. || Сортировка пузырьком.
start_time = time.time()

list3 = matrix.copy()

for row in range(len(list3)):
    for i in range(len(list3[row])-1):
        for k in range(len(list3[row]) - i - 1):
            if list3[row][k] > list3[row][k + 1]:
                list3[row][k], list3[row][k + 1] = list3[row][k + 1], list3[row][k]

print(list3)
            

print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[203 205 210 ... 441 445 446]
 [201 211 213 ... 444 445 449]
 [203 204 205 ... 442 442 443]
 ...
 [200 211 212 ... 443 448 449]
 [207 211 216 ... 440 441 449]
 [200 202 203 ... 442 445 448]]
--- 1026 ms ---


In [19]:
# Сортировка Шелла.
start_time = time.time()

list4 = matrix.copy() 

for row in range(len(list4)):
    for num in range(len(list4[row])):
        d = len(list4[row]) // 2
        while d >= 1:
            for i in range(len(list4[row]) - d):
                if list4[row][i] > list4[row][i + d]:
                    list4[row][i], list4[row][i + d] = list4[row][i + d], list4[row][i]
            d = d // 2
print(list4)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[203 205 210 ... 441 445 446]
 [201 211 213 ... 444 445 449]
 [203 204 205 ... 442 442 443]
 ...
 [200 211 212 ... 443 448 449]
 [207 211 216 ... 440 441 449]
 [200 202 203 ... 442 445 448]]
--- 5670 ms ---


In [21]:
# Быстрая сортировка.
start_time = time.time()
list5 = matrix.copy()
def quick_sort(arr):
    if len(arr) <= 1:
        return arr
    else:
        pivot = arr[0]
        less = [x for x in arr[1:] if x <= pivot]
        greater = [x for x in arr[1:] if x > pivot]
        return quick_sort(less) + [pivot] + quick_sort(greater)

for i in range(len(list5)):
    list5[i] = quick_sort(list5[i])

print(list5)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))
    

[[203 205 210 ... 441 445 446]
 [201 211 213 ... 444 445 449]
 [203 204 205 ... 442 442 443]
 ...
 [200 211 212 ... 443 448 449]
 [207 211 216 ... 440 441 449]
 [200 202 203 ... 442 445 448]]
--- 44 ms ---


In [22]:
# Турнирная сортировка.
start_time = time.time()
list6 = matrix.copy()
def heapify(arr, num, row):
    largest = row
    left = 2 * row + 1
    right = 2 * row + 2

    if left < num and arr[row] < arr[left]:
        largest = left

    if right < num and arr[largest] < arr[right]:
        largest = right

    if largest != row:
        arr[row], arr[largest] = arr[largest], arr[row]

        heapify(arr, num, largest)

def heapsort(arr):
    num = len(arr)

    for row in range(num // 2, -1, -1):
        heapify(arr, num, row)

    for i in range(num - 1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)
    
    return arr

for i in range(len(list6)):
    list6[i] = heapsort(list6[i])

print(list6)
print("--- {0} ms ---".format(round((time.time() - start_time)*1000)))

[[203 205 210 ... 441 445 446]
 [201 211 213 ... 444 445 449]
 [203 204 205 ... 442 442 443]
 ...
 [200 211 212 ... 443 448 449]
 [207 211 216 ... 440 441 449]
 [200 202 203 ... 442 445 448]]
--- 112 ms ---


### Вывод


В данной лабораторной работе мы разобрали 6 алгоритмов сортировок. Самой быстрой оказалась быстрая сортировка, самой медленной - Шелла.